# Generated by Django 5.2.7 on 2025-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='paintings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medium', models.CharField(choices=[('oil', 'Oil'), ('acrylic', 'Acrylic'), ('watercolor', 'Watercolor'), ('digital', 'Digital'), ('mixed_media', 'Mixed Media'), ('pen', 'Pen')], max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('material', models.CharField(choices=[('canvas', 'Canvas'), ('paper', 'Paper'), ('wood', 'Wood'), ('metal', 'Metal'), ('fabric', 'Fabric')], max_length=100)),
                ('availability', models.CharField(choices=[('original', 'Original'), ('print', 'Print'), ('both', 'Both'), ('not available', 'Not Available')], max_length=100)),
            ],
        ),
    ]
