# Generated by Django 5.2.7 on 2025-10-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
